feat: add  BaseSelect
tenadopt/custom-components-lib pull request #3
Opened 2024-05-23 06:42 UTC by tenadopt

2024-05-23 06:56 UTC, shev7 requested changes

2024-05-23 06:56 UTC, shev7 commented on src/components/BaseSelect/BaseSelect.tsx
> +        setOpen(!open);
```suggestion
        setOpen((prev) => !prev);
```

2024-05-23 06:56 UTC, shev7 commented on src/components/BaseSelect/BaseSelect.tsx
> +import ArrowIcon from '../Icon/ArrowIcon';
```suggestion
import ArrowIcon from 'assets/icons/arrow-icon.svg';
```

2024-05-23 06:56 UTC, shev7 commented on src/components/BaseSelect/BaseSelect.tsx
> +                    </button>
<IconButton/

2024-05-23 06:56 UTC, shev7 commented on src/components/BaseSelect/BaseSelect.tsx
> +                <div ref={divRef} className={optionsContainer}>
role listbox

2024-05-23 06:56 UTC, shev7 commented on src/utils/useOutsideClick.ts
> +export const useOutsideClick = (ref: RefObject<HTMLElement>, callback: () => void) => {
```suggestion
export const useOutsideClick = <T extends HTMLElement>(callback: () => void) => {
```

2024-05-23 08:21 UTC, tenadopt commented on src/components/BaseSelect/BaseSelect.tsx
> +        setOpen(!open);
Done

2024-05-23 08:22 UTC, tenadopt commented on src/components/BaseSelect/BaseSelect.tsx
> +import ArrowIcon from '../Icon/ArrowIcon';
Done

2024-05-23 08:22 UTC, tenadopt commented on src/components/BaseSelect/BaseSelect.tsx
> +                <div ref={divRef} className={optionsContainer}>
done

2024-05-23 08:54 UTC, tenadopt commented on src/utils/useOutsideClick.ts
> +export const useOutsideClick = (ref: RefObject<HTMLElement>, callback: () => void) => {
Done

2024-05-24 09:34 UTC, shev7 commented on src/components/BaseButton/BaseButton.tsx
> +        <button type="button" className={btn} {...props}>
```suggestion
        <button type="button" className={btnClasses} {...props}>
```

2024-05-24 09:34 UTC, shev7 commented on src/components/Icon/IconButton.tsx
> +            style={{ backgroundColor: 'transparent', borderColor: 'transparent' }}
Avoid using inline styles

2024-05-24 10:45 UTC, tenadopt commented on src/components/BaseButton/BaseButton.tsx
> +        <button type="button" className={btn} {...props}>
Done

2024-05-27 07:42 UTC, tenadopt commented on src/components/Icon/IconButton.tsx
> +            style={{ backgroundColor: 'transparent', borderColor: 'transparent' }}
Done

2024-05-28 06:05 UTC, shev7 approved these changes

2024-05-28 08:18 UTC, merged